#ifndef ERROR_CODES_H
#define ERROR_CODES_H

enum class ErrorCodes {
    BUFFER_OVERFLOW,
    BUFFER_UNDERFLOW,
    UNSUPPORTED_WEIGHT_TYPE,
    FILE_OPEN_FAILED,
    FILE_READ_FAILED,
    LAYERNAME_MISMATCH,
    LOAD_WEIGHTS_FAILED,
    INVALID_DIMENSION,
    INVALID_ARGUMENT,
    DIMENSION_MISMATCH,
    UNSUPPORTED_PARAMETER,
    CONVERT_WEIGHT_FAILED,
    SERIALIZATION_FAILED,
    TYPE_MISMATCH,
    OUT_OF_RANGE,
    NOT_FOUND,
    NONE,
};

#endif